// <auto-generated />
using ECChkAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECChkAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201118090948_initailRDS")]
    partial class initailRDS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECChkAPI.Models.IFECCUTF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECCabinetBarcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECCabinetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcCode1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcCode2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcLayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndThreeYard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IFECCUTFs");
                });
#pragma warning restore 612, 618
        }
    }
}
